### ISSUE TITLE
Does this Library Support Wi-Fi Device Discovery?

### ISSUE THREAD

**Issue by drewcovi** [telerik/ios-device-lib#46]
Xcode supports device discovery and debugging over wifi. Does this library facilitate such device discovery? the xcode command line tools include `instruments -s devices` which lists devices connected wirelessly.

**Comment by rosen-vladimirov** [comment]
Hey @drewcovi , 
Currently the library does not support Wi-Fi Device Discovery. More information can be found here: https://github.com/NativeScript/nativescript-cli/issues/4252#issuecomment-458909059

**Comment by drewcovi** [comment]
Excellent. I’ll track progress there.

**Comment by drewcovi** [comment]
Thanks!
