### ISSUE TITLE
Error spawn fails ENOENT

### ISSUE THREAD

**Issue by SylvatiCodes** [telerik/ios-device-lib#72]
Upon running ```ns device``` (or indeed any nativescript command) I get back 
```sh
Connected devices & emulators
Searching for devices...
Error: spawn /home/foo/.nvm/versions/node/v14.15.4/lib/node_modules/nativescript/node_modules/ios-device-lib/bin/linux/x64/ios-device-lib ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
I have tried using different node versions (12.20.1 as well as 14.15.3) with the same error occurring.

I haven't tried installing straight node from the Arch repositories yet. I have tried installing android-studio with no difference (only had android-tools and android-udev previously and it worked previous to now)

**Comment by SylvatiCodes** [comment]
ns device would not work but ns run works?

**Comment by baermathias** [comment]
@PatrickLohan How did you solve it? I have the same issue

**Comment by SylvatiCodes** [comment]
Without knowing your setup and what the logs say I can't really help but...

Have you tried turning it off and on again? Also, if you are using nvm make sure you're on the latest lts and that all your required global packages have been reinstalled for that version. Then reboot again.

**Comment by baermathias** [comment]
`ns device android` works for me
https://github.com/NativeScript/NativeScript/issues/9272

**Comment by SylvatiCodes** [comment]
Seems to be the same things the linked issue.

I updated node at some point and maybe that was part or all of the problem.
